apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evilfactorylabs.social
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: evilfactorylabs-social
    name: heavy-rotation
  project: evilfactorylabs.social
  source:
    path: evilfactorylabs.social
    repoURL: https://github.com/evilfactorylabs/archmage
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
