apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-heavy-rotation
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    name: heavy-rotation
  project: evilfactorylabs.social
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.10.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
